baolong:
  social:
    websocket:
      port: 8899

server:
  port: 8800
  servlet:
    context-path: /chat

spring:
  application:
    name: bl-social-chat
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${baolong.social.mysql.ip}:${baolong.social.mysql.port}/${baolong.social.mysql.dbname}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${baolong.social.mysql.username}
    password: ${baolong.social.mysql.password}
  data:
    redis:
      host: ${baolong.social.redis.host}
      port: ${baolong.social.redis.port}
      database: ${baolong.social.redis.database}
      password: ${baolong.social.redis.password}
      # 连接超时时间（单位: 毫秒, 30分钟）
      timeout: 1800000
      jedis:
        pool:
          enabled: true
          min-idle: 10
          max-idle: 100
          max-active: 100
          max-wait: -1
  ############### 邮箱配置 ###############
  mail:
    host: ${baolong.social.email.host}
    port: ${baolong.social.email.port}
    nickname: ${baolong.social.email.nickname}
    username: ${baolong.social.email.username}
    password: ${baolong.social.email.password}
    protocol: ${baolong.social.email.protocol}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: ${spring.social.email.port}
            class: javax.net.ssl.SSLSocketFactory

################ MyBatis-Plus ###############
mybatis-plus:
  # mapper 文件位置
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    # 日志配置
    log-impl: ${baolong.log.mybatis.plus.log.impl}
  # 全局配置
  global-config:
    # 是否开启启动打印的 LOGO
    banner: false
    db-config:
      # 表名是否使用下划线命名
      table-underline: true
      # 全局逻辑删除的实体字段名
      logic-delete-field: isDelete
      # 逻辑已删除值（默认为 1）
      logic-delete-value: 1
      # 逻辑未删除值（默认为 0）
      logic-not-delete-value: 0

################ 日志 ###############
logging:
  config: classpath:logback-spring.xml
  file:
    path: ${baolong.log.logging.file.path}
